class ChargesController < ApplicationController
	before_action :authenticate_user!
	def new
		@cart = current_user.cart
		@cart_products = @cart.products

		@amount = 0
        @cart_products = current_user.cart.cartProducts
        @cart_products.each do |cart_product|
        	@amount +=  cart_product.product.price * cart_product.quantity
    	end
	end

	def create
	  @cart = current_user.cart
	  # .to_i to avoid the bug generated by the decimal
	 	@amount = @cart.total_price.to_i

	  customer = Stripe::Customer.create({
	  	email: params[:stripeEmail],
	  	source: params[:stripeToken],
	  })

	  charge = Stripe::Charge.create({
	  	customer: customer.id,
	  	amount: @amount * 100,
	  	description: 'Rails Stripe customer',
	  	currency: 'eur',
	  })

		# We stock the cart's items in a variable
		@cart_products = @cart.products

		# We create a new order
		@command = Command.create(stripe_customer_id: customer.id, customer_id: current_user.id)

		# Each item of this card is put in the order item table (with the id of the current orde

		# we empty the cart
		CartProduct.where(cart_id: @cart.id).each do |entry|
			entry.destroy
		end

		redirect_to commands_path

		rescue Stripe::CardError => e
			flash[:error] = e.message
			redirect_to new_charge_path
		end
end
